### PR TITLE
Streamlit demo

### PR DESCRIPTION
**Pull request by VolcanoBlue13**
To run this:

- [x] `pip install -r requirements.txt`

- [x] `streamlit run streamlit_six_nations_demo.py`

### CODE REVIEW

**Comment by VolcanoBlue13** [comment]
Hi @india-kerle , would you mind testing this runs? I haven't added in all the comments, so I won't merge just yet, but just wanted to check that it works okay!

**Review by india-kerle — APPROVED** [review]
fabbo looks great! I was able to run the script. Did you want me to add password protection or you think it's fine as is?

**Comment by india-kerle** [comment]
oh also - it would be great if you had a README.md summarising streamlit, what its used for etc.

**Comment by VolcanoBlue13** [comment]
Yes that would be amazing if you could add a password, thanks India!

**Comment by VolcanoBlue13** [comment]
Will also add a README :)

**Pull request merged**
